name: Generate Snake Animation

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Also runs on every push to the main branch
  push:
    branches:
      - main

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest
    steps:
      # This step generates the snake SVGs
      - uses: Platane/snk@v3
        with:
          # Get your GitHub username automatically
          github_user_name: ${{ github.repository_owner }}
          
          # A list of files to generate
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # This step pushes the generated files to the 'output' branch
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
